[ko]
rust = "러스트"
ownership = "소유권"

[ko-postpos]
postpos = [ # 왼쪽은 받침이 없을때, 오른쪽은 받침이 있을때
    ["는", "은"],
    ["가", "이"],
    ["를", "을"],
    ["와", "과"],
    ["로", "으로"],
    ["로서", "으로서"],

    # 똑같은 녀석들은 아래쪽에 정리해둡니다
    ["의", "의"],
    ["에서", "에서"],
    ["에서는", "에서는"],
    ["이란", "이란"],
    ["에", "에"],
    ["입니다", "입니다"],
]